source: _jekyll
destination: site

url: https://ticklethepanda.co.uk

assetsUrl: /assets
imagesUrl: https://images.ticklethepanda.co.uk
apiUrl: https://api.ticklethepanda.co.uk
apiHealthUrl: https://health-ticklethepanda.herokuapp.com

